import fs from "fs";
import path from "path";
import matter from "gray-matter";

const THESES_DIR = path.join(process.cwd(), "content/Theses");
const PROCESSED_DIR = path.join(process.cwd(), "content/Processed");
const SOURCE_URLS_PATH = path.join(process.cwd(), "content/source-urls.json");

// Load source URL mapping (generated by scripts/generate-source-urls.py)
let sourceUrlMap: Record<string, string> = {};
try {
  if (fs.existsSync(SOURCE_URLS_PATH)) {
    sourceUrlMap = JSON.parse(fs.readFileSync(SOURCE_URLS_PATH, "utf-8"));
  }
} catch {
  // Silently fall back to empty map if file doesn't exist or is malformed
}

export interface Thesis {
  slug: string;
  title: string;
  content: string;
  maturity: "Hypothesis" | "Emerging" | "Established" | "Conviction";
  take: string;
  sources: Source[];
}

export interface Source {
  slug: string;
  title: string;
  content: string;
  date?: string;
  type?: string;
  folder?: string;
}

export interface SourceWithBacklinks extends Source {
  backlinks: { slug: string; title: string; maturity: Thesis["maturity"] }[];
}

function extractMaturity(content: string): Thesis["maturity"] {
  const maturityMatch = content.match(
    /\*\*Maturity:\*\*\s*(Hypothesis|Emerging|Established|Conviction)/i
  );
  if (maturityMatch) {
    return maturityMatch[1] as Thesis["maturity"];
  }
  // Try table format
  const tableMatch = content.match(
    /\|\s*Maturity\s*\|\s*(Hypothesis|Emerging|Established|Conviction)/i
  );
  if (tableMatch) {
    return tableMatch[1] as Thesis["maturity"];
  }
  return "Hypothesis";
}

function extractTake(content: string): string {
  // Look for "The Take" or "## The Take" section
  const takeMatch = content.match(
    /(?:##?\s*)?(?:The\s+)?Take[:\s]*\n+([\s\S]*?)(?=\n##|\n\*\*|$)/i
  );
  if (takeMatch) {
    // Get first paragraph
    const firstPara = takeMatch[1].split("\n\n")[0].trim();
    return firstPara.slice(0, 300) + (firstPara.length > 300 ? "..." : "");
  }
  // Fallback: first paragraph after title
  const lines = content.split("\n").filter((l) => l.trim());
  for (const line of lines.slice(1)) {
    if (!line.startsWith("#") && !line.startsWith("|") && line.length > 50) {
      return line.slice(0, 300) + (line.length > 300 ? "..." : "");
    }
  }
  return "";
}

function extractSources(content: string): string[] {
  const sources: string[] = [];
  // Look for wikilinks in evidence tables or citations
  const wikilinks = content.match(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g);
  if (wikilinks) {
    for (const link of wikilinks) {
      const match = link.match(/\[\[([^\]|]+)/);
      if (match) {
        sources.push(match[1]);
      }
    }
  }
  return Array.from(new Set(sources));
}

/**
 * Sanitize thesis content for external/public viewing:
 * - Remove blockquotes attributed to non-public sources (interviews, operator calls, expert networks)
 * - Remove Tegus/expert network references
 * - Remove ## Related Theses section
 * - Remove everything after Open Questions section (Evidence, Confidence, etc.)
 * - Strip wiki links [[...]]
 * - Remove first H1 if it matches the title (prevents duplicate title)
 */
function sanitizeForExternal(content: string, title: string): string {
  let sanitized = content;

  // --- Phase 1: Scrub non-public source attributions from blockquotes ---

  // For blockquotes with "— Attribution" at the end, replace non-public attributions
  // with "Internal research". Keep public ones (earnings calls, press releases, named execs).
  //
  // Public attribution patterns we KEEP:
  //   - "Tim Noel, UHC CEO, Q4 2025 earnings" (named exec + earnings)
  //   - "HCHB Press Release, Sept 2025" (press releases)
  //   - "Quanterix Q3 2025 Results" (public earnings/results)
  //   - "pi-0 open source release" (public announcements)
  //   - Published paper titles
  //
  // Non-public patterns we REPLACE → "Internal research":
  //   - "ETK Payment Integrity 2024" (purchased reports)
  //   - "Industry analysis/research/operator" (internal)
  //   - "ACO operator", "Agency owner" (anonymized interviews)
  //   - "Former VP..., industry interview" (proprietary interviews)
  //   - "investor presentation/deck" (non-public materials)

  const publicAttributionPatterns = [
    /earnings/i,
    /\bQ[1-4]\b/i,
    /press\s+release/i,
    /announcement/i,
    /\blaunch\b/i,
    /open\s+source/i,
    /\bCEO\b|\bCFO\b|\bCTO\b|\bCOO\b/,
  ];

  // Non-public patterns that override the length heuristic
  const nonPublicPatterns = [
    /tegus/i,
    /industry interview/i,
    /operator interview/i,
    /expert call/i,
    /investor presentation/i,
    /investor deck/i,
  ];

  function isPublicAttribution(attr: string): boolean {
    // Explicitly non-public sources are always replaced, even if long
    if (nonPublicPatterns.some((p) => p.test(attr))) return false;
    // Known public source patterns
    if (publicAttributionPatterns.some((p) => p.test(attr))) return true;
    // Long attributions (>40 chars) are likely published paper titles, not internal sources
    if (attr.trim().length > 40) return true;
    return false;
  }

  // Replace non-public blockquote attributions with "Internal research"
  // Use greedy .* so we match the LAST " — " (the attribution separator),
  // not an em-dash inside the quote text (e.g., "billing—both")
  sanitized = sanitized.replace(
    /^(>.*)\s+—\s+(.+)$/gm,
    (_match, quote, attribution) => {
      if (isPublicAttribution(attribution)) {
        return `${quote} — ${attribution}`;
      }
      return `${quote} — Internal research`;
    }
  );

  // Remove entire blockquotes from proprietary interviews/operator calls
  // (these reveal methodology, not just attribution)
  sanitized = sanitized.replace(
    /(?:^>.*\n)*^>.*(?:industry interview|operator interview|expert call|tegus call|tegus|investor presentation|investor deck).*$\n*/gim,
    ""
  );

  // Remove inline "Tegus expert calls" references
  sanitized = sanitized.replace(
    /(?:,?\s*(?:and\s+)?)?Tegus\s+expert\s+calls?/gi,
    ""
  );

  // Remove inline interview attributions in non-blockquote text
  sanitized = sanitized.replace(
    /\s*—\s*(?:Former\s+)?[\w\s]+,\s*(?:industry interview|operator interview|expert call)\s*/gi,
    ""
  );

  // Generalize titled operators at named orgs in inline prose
  // "CPO at Cone Health:" → "Health system pharmacy leaders:"
  // "Northwestern IT pharmacist:" → "Health system IT leaders:"
  const titleReplacements: [RegExp, string][] = [
    [/\bCPO(?:\s+at\s+[A-Z][\w\s]*?)(?=:|\s+says?\b|\s+chose\b|\s+would\b)/g, "Health system pharmacy leaders"],
    [/\b(?:IT\s+[Pp]harmacist|IT\s+director)(?:\s+at\s+[A-Z][\w\s]*?)(?=:|\s+says?\b)/g, "Health system IT leaders"],
    [/\bCMIO(?:\s+at\s+[A-Z][\w\s]*?)(?=:|\s+says?\b)/g, "Health system informatics leaders"],
  ];
  for (const [pattern, replacement] of titleReplacements) {
    sanitized = sanitized.replace(pattern, replacement);
  }

  // Generalize specific health system vendor migration plans
  // "Northwestern planning to phase out CoverMyMeds for Latent" → generic
  sanitized = sanitized.replace(
    /\b[A-Z][a-z]+(?:Health|Medical|Children's)?\s+planning to phase out\s+\w+\s+for\s+\w+/g,
    "Major health systems are phasing out legacy tools for AI-native alternatives"
  );

  // Also catch "[HealthSystem] IT pharmacist:" without "at"
  sanitized = sanitized.replace(
    /\b(?:Northwestern|MaineHealth|LifePoint|Ochsner|MetroHealth)\s+(?:IT\s+)?(?:pharmacist|CMIO|CIO|director)/gi,
    "Health system IT leaders"
  );

  // --- Phase 2: Strip structural sections ---

  // Remove ## Related Theses section entirely (wiki links would render as broken)
  sanitized = sanitized.replace(
    /\n+---\n+## Related Theses[\s\S]*?(?=\n+---\n|\n+\*Confidence|$)/i,
    ""
  );
  // Also catch without leading ---
  sanitized = sanitized.replace(
    /\n+## Related Theses[\s\S]*?(?=\n+---\n|\n+\*Confidence|$)/i,
    ""
  );

  // Truncate after Open Questions section
  // Keep Open Questions but remove Evidence, Confidence, and anything after
  const openQuestionsMatch = sanitized.match(
    /(## Open Questions[\s\S]*?)(?=\n---\n\n## Evidence|\n## Evidence|\n---\n\n\*Confidence|\n\*Confidence|$)/i
  );
  if (openQuestionsMatch) {
    const beforeOpenQuestions = sanitized.substring(
      0,
      sanitized.indexOf("## Open Questions")
    );
    sanitized = beforeOpenQuestions + openQuestionsMatch[1].trim();
  } else {
    // Fallback: just cut at Evidence or Confidence
    const evidenceIdx = sanitized.indexOf("\n## Evidence");
    const confidenceIdx = sanitized.search(/\n\*Confidence:/);
    const cutIdx = Math.min(
      evidenceIdx > 0 ? evidenceIdx : Infinity,
      confidenceIdx > 0 ? confidenceIdx : Infinity
    );
    if (cutIdx !== Infinity) {
      sanitized = sanitized.substring(0, cutIdx).trim();
    }
  }

  // Catch any remaining *Confidence: lines that survived truncation
  sanitized = sanitized.replace(/^\*Confidence:[\s\S]*$/gm, "");

  // --- Phase 3: Resolve wiki links and image embeds ---

  // ![[image.png]] → ![](/images/image.png) for Obsidian image embeds
  sanitized = sanitized.replace(
    /!\[\[([^\]]+\.(?:png|jpg|jpeg|gif|svg|webp))\]\]/gi,
    (_match, filename: string) => {
      return `![](${encodeURI(`/images/${filename}`)})`;
    }
  );

  // [[path|display text]] → [display text](url) if URL exists, otherwise plain display text
  sanitized = sanitized.replace(
    /\[\[([^\]|]+)\|([^\]]+)\]\]/g,
    (_match, wikiPath: string, display: string) => {
      const url = sourceUrlMap[wikiPath.trim()];
      if (url) {
        return `[${display}](${url})`;
      }
      return display;
    }
  );

  // [[path]] → [filename](url) if URL exists, otherwise strip
  sanitized = sanitized.replace(
    /\[\[([^\]]+)\]\]/g,
    (_match, wikiPath: string) => {
      const url = sourceUrlMap[wikiPath.trim()];
      if (url) {
        // Use the last segment of the path as display text
        const parts = wikiPath.split("/");
        const display = parts[parts.length - 1].trim();
        return `[${display}](${url})`;
      }
      return "";
    }
  );

  // Strip internal-only entries from ## Sources section (bullets without a public link)
  const sourcesMatch = sanitized.match(/(## Sources\n)([\s\S]*?)(\n---|\n## |\n\*Confidence|$)/i);
  if (sourcesMatch) {
    const sourcesLines = sourcesMatch[2].split("\n");
    const publicOnly = sourcesLines.filter(
      (line) => !line.startsWith("- ") || /\[.*?\]\(.*?\)/.test(line)
    );
    sanitized = sanitized.replace(
      sourcesMatch[0],
      sourcesMatch[1] + publicOnly.join("\n") + sourcesMatch[3]
    );
  }

  // Clean up orphaned citation markers
  sanitized = sanitized.replace(/>\s*\n>\s*$/gm, "");

  // Clean up multiple consecutive blank lines (from removed blockquotes)
  sanitized = sanitized.replace(/\n{3,}/g, "\n\n");

  // Remove first H1 if it matches the title (prevents duplicate title)
  const h1Match = sanitized.match(/^# (.+)\n/);
  if (h1Match) {
    const h1Title = h1Match[1].trim();
    if (h1Title.toLowerCase() === title.toLowerCase()) {
      sanitized = sanitized.replace(/^# .+\n+/, "");
    }
  }

  return sanitized.trim();
}

export function getAllTheses(): Thesis[] {
  if (!fs.existsSync(THESES_DIR)) {
    return [];
  }

  const files = fs.readdirSync(THESES_DIR).filter((f) => f.endsWith(".md"));

  return files
    .map((filename) => {
      const filePath = path.join(THESES_DIR, filename);
      const fileContent = fs.readFileSync(filePath, "utf-8");
      const { content } = matter(fileContent);

      const slug = filename.replace(".md", "");
      // Title is the slug itself (filenames are now human-readable)
      const title = slug;

      // Skip empty files or files named "Theses"
      if (!content.trim() || slug.toLowerCase() === "theses") {
        return null;
      }

      return {
        slug,
        title,
        content: sanitizeForExternal(content, title),
        maturity: extractMaturity(content),
        take: extractTake(content),
        sources: [],
      };
    })
    .filter((t): t is NonNullable<typeof t> => t !== null);
}

export function getThesis(slug: string): Thesis | null {
  // Block access to "Theses" file
  if (slug.toLowerCase() === "theses") {
    return null;
  }

  const filePath = path.join(THESES_DIR, `${slug}.md`);

  if (!fs.existsSync(filePath)) {
    return null;
  }

  const fileContent = fs.readFileSync(filePath, "utf-8");
  const { content } = matter(fileContent);

  // Skip empty files
  if (!content.trim()) {
    return null;
  }

  const title = slug;

  // Note: We extract sources from raw content before sanitizing
  const sourceNames = extractSources(content);
  const sources = sourceNames
    .map((name) => getSource(name))
    .filter((s): s is Source => s !== null);

  return {
    slug,
    title,
    content: sanitizeForExternal(content, title),
    maturity: extractMaturity(content),
    take: extractTake(content),
    sources,
  };
}

export function getSource(name: string): Source | null {
  // Try direct path
  let filePath = path.join(PROCESSED_DIR, `${name}.md`);

  if (!fs.existsSync(filePath)) {
    // Try finding in subdirectories
    const searchDirs = [PROCESSED_DIR];
    for (const dir of searchDirs) {
      if (!fs.existsSync(dir)) continue;
      const found = findFile(dir, `${name}.md`);
      if (found) {
        filePath = found;
        break;
      }
    }
  }

  if (!fs.existsSync(filePath)) {
    return null;
  }

  const fileContent = fs.readFileSync(filePath, "utf-8");

  try {
    const { content, data } = matter(fileContent);
    // gray-matter auto-parses dates to Date objects, convert back to string
    // Check both 'date' and 'published' fields
    const rawDate = data.date || data.published;
    let dateStr: string | undefined;
    if (rawDate) {
      dateStr = rawDate instanceof Date ? rawDate.toISOString().split('T')[0] : String(rawDate);
    }
    return {
      slug: name,
      title: data.title || name.replace(/-/g, " "),
      content,
      date: dateStr,
    };
  } catch {
    // If frontmatter parsing fails, return content as-is
    // Strip any malformed frontmatter
    const contentWithoutFrontmatter = fileContent.replace(/^---[\s\S]*?---\n?/, "");
    return {
      slug: name,
      title: name.replace(/-/g, " "),
      content: contentWithoutFrontmatter,
    };
  }
}

function findFile(dir: string, filename: string): string | null {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findFile(fullPath, filename);
      if (found) return found;
    } else if (entry.name === filename) {
      return fullPath;
    }
  }
  return null;
}

export function getAllSources(): Source[] {
  if (!fs.existsSync(PROCESSED_DIR)) {
    return [];
  }

  const sources: Source[] = [];

  function walkDir(dir: string, folder: string = "") {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walkDir(fullPath, entry.name);
      } else if (entry.name.endsWith(".md")) {
        const fileContent = fs.readFileSync(fullPath, "utf-8");
        const slug = entry.name.replace(".md", "");

        try {
          const { content, data } = matter(fileContent);
          // gray-matter auto-parses dates to Date objects, convert back to string
          // Check both 'date' and 'published' fields
          const rawDate = data.date || data.published;
          let dateStr: string | undefined;
          if (rawDate) {
            dateStr = rawDate instanceof Date ? rawDate.toISOString().split('T')[0] : String(rawDate);
          }
          sources.push({
            slug,
            title: data.title || slug.replace(/-/g, " "),
            content,
            date: dateStr,
            type: data.type,
            folder: folder || undefined,
          });
        } catch {
          // Handle malformed frontmatter
          const contentWithoutFrontmatter = fileContent.replace(/^---[\s\S]*?---\n?/, "");
          sources.push({
            slug,
            title: slug.replace(/-/g, " "),
            content: contentWithoutFrontmatter,
            folder: folder || undefined,
          });
        }
      }
    }
  }

  walkDir(PROCESSED_DIR);
  return sources;
}

export function getSourceWithBacklinks(slug: string): SourceWithBacklinks | null {
  const source = getSource(slug);
  if (!source) return null;

  // Find all theses that cite this source
  const theses = getAllTheses();
  const backlinks: SourceWithBacklinks["backlinks"] = [];

  for (const thesis of theses) {
    const thesisPath = path.join(THESES_DIR, `${thesis.slug}.md`);
    if (!fs.existsSync(thesisPath)) continue;

    const content = fs.readFileSync(thesisPath, "utf-8");
    // Check if this thesis cites the source
    if (content.includes(`[[${slug}]]`) || content.includes(`[[${slug}|`)) {
      backlinks.push({
        slug: thesis.slug,
        title: thesis.title,
        maturity: thesis.maturity,
      });
    }
  }

  // Get folder info
  let folder: string | undefined;
  const found = findFileWithPath(PROCESSED_DIR, `${slug}.md`);
  if (found) {
    const relativePath = path.relative(PROCESSED_DIR, found);
    const parts = relativePath.split(path.sep);
    if (parts.length > 1) {
      folder = parts[0];
    }
  }

  return {
    ...source,
    folder,
    backlinks,
  };
}

function findFileWithPath(dir: string, filename: string): string | null {
  if (!fs.existsSync(dir)) return null;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findFileWithPath(fullPath, filename);
      if (found) return found;
    } else if (entry.name === filename) {
      return fullPath;
    }
  }
  return null;
}
